data:
  csv_file_path: ./archive/imdb-dataset.csv
  test_set_ratio: 0.3
  train_csv_save_path: ./archive/train.csv
  test_csv_save_path: ./archive/test.csv

features:
  vectorizer: count-vectorizer
  train_features_save_path: ./archive/train.joblib
  test_features_save_path: ./archive/test.joblib

